apiVersion: v1
name: kiam
version: 2.5.1
appVersion: 3.3
description: Integrate AWS IAM with Kubernetes
keywords:
  - kiam
  - aws
  - iam
  - security
home: https://github.com/uswitch/kiam
sources:
  - https://github.com/uswitch/kiam
maintainers:
  - name: uswitch
    email: cloud@uswitch.com
engine: gotpl
